# makefile

server:
	java -jar vendor/selenium-server-standalone/selenium-server-standalone-2.28.0.jar

screenshot-all:
	php screenshot-all-plugins.php 

screenshot-all-firefox:
	php screenshot-all-plugins.php driverName=firefox
